version: '3'

services:
  nginx:
    image: nginx
    ipc: shareable
    volumes:
      - ./web:/srv:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - cgintonic_socket:/var/socket
    ports:
      - 80:80
  cgintonic:
    image: node:12
    working_dir: /app
    command: -e "require('./lib/cgintonic')"
    ipc: shareable
    volumes:
      - .:/app:ro
      - ./web:/srv:ro
      - cgintonic_socket:/var/socket

volumes:
  cgintonic_socket: